### ISSUE TITLE
Custom color map popup broken

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#99] opened 2017-04-13 21:53 UTC
_Commit_:  http://higlass.io/app/?config=Wxxdw3aDTwyyx9TweoxWWQ

#### Steps to reproduce
1. http://higlass.io/app/?config=Wxxdw3aDTwyyx9TweoxWWQ
2. Try to open the custom color map

#### Observed behavior
- Nothing happens 😱

#### Expected behavior
- The color map dialog should open.  😶

**Comment by pkerpedjiev** [comment] 2017-09-01 18:30
Duplicate of https://github.com/hms-dbmi/higlass/issues/116

**Closed by pkerpedjiev** 2017-09-01 18:30 UTC
Labels: bug
