### ISSUE TITLE
JSON config drop event unresponsive after initial drop

### ISSUE THREAD

**Issue by alexpreynolds** [hms-dbmi/higlass#265] opened 2018-06-05 19:39 UTC
_Commit_: v0.6.26 of higlass-website, v1.6.3 of higlass-server, v1.0.0-alpha.12 of higlass

#### Steps to reproduce
1. Set up _multivec_ track as _horizontal-stacked-bar_ type
2. Zoom to region of interest, e.g., CTCF or APOE
3. Pan and zoom, and export a JSON config from the current view state
4. Reload the site
5. Drag-and-drop the JSON config file onto the Chrome browser window
6. Pan and zoom to change the current view state
7. Again drag-and-drop the JSON config file onto the Chrome browser window

#### Observed behavior
- On the first attempt, the view is launched and configured from data in the JSON config file
- Subsequent attempts to drop the JSON config file do not relaunch/reconfigure the current view
- Reloading the higlass viewer to clear state seems to reset things and allows drag-and-drop to work 

https://youtu.be/55HGyqnmA1A

I am using Google Chrome v67.0.3396.62 (OS X) for testing, which is current as of writing this.

#### Expected behavior
- Dropping a JSON config file should update the current view to the tracks and domain settings in the config file

**Comment by flekschas** [comment] 2018-06-22 21:54
Thanks for reporting. Did you test other tracks as well? I'd imagine it's unrelated to multivec and rather an issue of reloading the config.

**Comment by pkerpedjiev** [comment] 2018-09-19 15:12
I couldn't reproduce this. There's a good chance it got fixed in an earlier release. I'm going to close this issue for now but if it happens again, feel free to reopen.

**Closed by pkerpedjiev** 2018-09-19 15:12 UTC
Labels: bug
