### ISSUE TITLE
Export link doesn't include port number

### ISSUE THREAD

**Issue by nvictus** [hms-dbmi/higlass#134] opened 2017-08-31 01:04 UTC
_Commit_: 

#### Steps to reproduce
1. Run HiGlass on non-80 port
2. Click export view as link

#### Observed behavior
- Link appears without port number

#### Expected behavior
- URL should include port number if not 80

**Comment by pkerpedjiev** [comment] 2017-10-26 21:46
Duplicate of https://github.com/hms-dbmi/higlass/issues/162

And fixed in `v0.2.32`.

**Closed by pkerpedjiev** 2017-10-26 21:46 UTC
